### ISSUE TITLE
Decrease opacity in Satellite layer

### ISSUE THREAD

**Issue by manoharuss** [osmlab/changeset-map#100]
Due to the natural colours on the satellite layer, it is a bit hard to spot the selected feature on the changeset map above satellite layer. It would be great if the opacity of the satellite layer is reduced to 60%.

@ajithranka @geohacker @batpad

**Comment by geohacker** [comment]
@manoharuss - should this be default?

**Comment by planemad** [comment]
Current:

![screenshot 2017-02-28 11 35 55](https://cloud.githubusercontent.com/assets/126868/23393621/1999993c-fdaa-11e6-9676-e8ef4f157d3d.png)

@manoharuss can you please post a screenshot of what a 60% opacity looks like so that we can compare?

**Comment by planemad** [comment]
Also since @rasagy @ajithranka implemented the current styling, please make sure the new hybrid style is a clear improvement over the dark style.

**Comment by rasagy** [comment]
I think right now the default map style is set to `satellite-streets-v9` instead of the dark style:

```
            if (layer === 'default') {
                renderMap('mapbox://styles/mapbox/satellite-streets-v9', result);
            }

            if (layer === 'dark') {
                renderMap('mapbox://styles/planemad/cijcefp3q00elbskq4cgvcivf', result);
            }

            if (layer === 'streets') {
                renderMap('mapbox://styles/mapbox/streets-v9', result);
            }
```

Let’s switch it to a custom map style that overlays satellite layer on a dark background. I’ll work on this and update the style on this ticket, and push to the repo if it works well.

cc @planemad @manoharuss @geohacker @ajithranka

**Comment by geohacker** [comment]
@rasagy ✌️ thank you!

**Comment by rasagy** [comment]
**What we should try and assess:**

- Example areas where our current changeset map style doesn’t work well (few screenshots would do)
- Understand how we want to use the satellite layer: We have control over opacity, saturation etc, let’s leverage that if needed
- Work on a solid satellite layer before we implement #89

cc @manoharuss @planemad

**Comment by rasagy** [comment]
[WIP Style here](https://api.mapbox.com/styles/v1/rasagy/cizp6lsah00ct2snu6gi3p16q.html?fresh=true&title=true&access_token=pk.eyJ1IjoicmFzYWd5IiwiYSI6Ilk2ay1VMEEifQ.CJfn_CxDfwyN5xaVfx4jaw#9.6/37.7850/-122.3243), will do a quick round of feedback with @manoharuss on the above questions.

**Comment by manoharuss** [comment]
@planemad Agree that distinguishing edits with the satellite hybrid layer is a bit hard right now.


**Satellite** 

- To check if the user has traced a feature that is distinguishable from the imagery.
- This was hard with previous dark layer as it would only show satellite after higher zoom levels. Because visualising large features such as forests and waterbodies.(If they exist on the ground and traced well)

**Streets**

- To check if something is wrong on the map quickly in that area.

**Dark**

- The dark style has worked for us a long time. The edits can be easily seen on the map, can be selected and visualised.

- But it lacks verifying with satellite imagery for bigger features that do not need zooming in to verify on the satellite imagery. Ex: If a large forest is edited. If I zoom in, I am only looking at a very small portion of the geometry and the trace quality in total cannot be seen.


I suggested a decrease in opacity of satellite layer to avoid above problems with distinguishing of edits over the satellite layer.

Will add example changesets to this comment.

cc @rasagy @planemad @geohacker

**Comment by manoharuss** [comment]
Current problem with satellite layer

![image](https://cloud.githubusercontent.com/assets/8921295/23399238/8e960804-fdc5-11e6-8891-c963b120ac0f.png)

_The modified edits blend too easily with motorways_

**Comment by rasagy** [comment]
### Changes made in the Satellite Layer:
- **Satellite layer**: Opacity reduced to 75% by z10, Saturation, Contrast & Brightness reduced to 75% by z12: Based on @manoharuss’s feedback, the imagery is mainly used to recognize objects, and color isn’t as important in this case.
- **Roads**: All roads are now white: In most cases, knowing that a road is a motorway/trunk isn’t as important as the existence of a road (this detail can be seen through the osm tag/Streets layer).
- **Labels**: Lower opacity so the white labels don’t stand out as much on the darker satellite layer, no color for park & water labels
- **Icons**: All icons are grayscale, lower opacity to match labels, highway badges are hidden, railway networks use a single common icon, more subtle default PoI icon (dot)

### Comparison:

![satelite-sat](https://cloud.githubusercontent.com/assets/1117531/24136736/2bbe33a6-0e36-11e7-9caa-6cfd70b39f19.gif)

Map style: `mapbox://styles/rasagy/cizp6lsah00ct2snu6gi3p16q`

**Comment by rasagy** [comment]
Here’s an example of two changesets ([1](http://osmlab.github.io/changeset-map/#45841809), [2](http://osmlab.github.io/changeset-map/#46705455)) on top of the old & new style:

![satelite-sat-compare](https://cloud.githubusercontent.com/assets/1117531/24138170/35b441f0-0e3d-11e7-9ac2-62d46856b8a2.gif)

Switching the layer options to:
- **Satellite** (Hybrid, shared above)
- **Dark** (Only Dark, no satellite on high zooms)
- **Streets** (Same as before)

Will push changes after 👀  from @manoharuss (might need a few more minor edits on the satellite layer opacity+brightness)

cc @ajithranka @geohacker @planemad
