### ISSUE TITLE
Satellite button not working in layer toggle when selecting from other layers

### ISSUE THREAD

**Issue by manoharuss** [osmlab/changeset-map#101]
![validation](https://cloud.githubusercontent.com/assets/8921295/23399072/ee06c48c-fdc4-11e6-87f1-48f6ff27c96f.gif)

Observed this during validation. The button seems to not work when trying to select from other layers. Opens by default only.

cc @geohacker @ajithranka @rasagy

**Comment by ajithranka** [comment]
Fixed in [2b5ecf8](https://github.com/osmlab/changeset-map/pull/107/commits/2b5ecf8f0bffd68400e5200af7857d6064a32047).
