### ISSUE TITLE
Show a better summary of changesets (needs discussion)

### ISSUE THREAD

**Issue by ajithranka** [osmlab/changeset-map#104]
Similar to how OSM shows a help summary of changesets in a left panel. This is useful to quickly get a sense of the changes.

<img width="337" alt="screen shot 2017-03-10 at 11 28 44 am" src="https://cloud.githubusercontent.com/assets/11095038/23783939/f9a49e50-0584-11e7-9d1b-fccc01cbaab5.png">

Source: http://www.openstreetmap.org/changeset/46729079

Please add your thoughts on:

- Which details are most useful?
- How these should be organized?

cc: @planemad @maning @geohacker @batpad @rasagy

**Comment by batpad** [comment]
*bump* would love to see this feature get some love.

I think it may also be super useful to add more depth to this summary, including a break-down by feature type, etc.

cc @maning

**Comment by planemad** [comment]
Two references that could help:
- OSM History Viewer http://osmhv.openstreetmap.de/changeset.jsp?id=47393150
- http://resultmaps.neis-one.org/osm-suspicious

**Comment by nrenner** [comment]
I also think some kind of additional grouping e.g. by feature type, action, key/tag changes would be helpful to get a better sense of the changes (ideally with a drill down to individual objects and synchronized with the map).

Some more examples in that direction:
- [OpenStreetMap Analytic Difference Engine](https://osm.expandable.dk/) ([GitHub](https://github.com/MichaelVL/osm-analytic-tracker), also mentioned in willemarcel/osmcha-django#68)
- <http://fred.dev.openstreetmap.org/coolnamegoeshere>
  Screenshot changeset 46729079:
  ![coolnamegoeshere-cs-46729079](https://user-images.githubusercontent.com/1092030/27386558-873f74f8-5696-11e7-80d4-76384074707b.png)

**Comment by planemad** [comment]
@nrenner some ideas and use cases of how you have been using either of these interfaces might help to figure out whats is the most important information to show.

**Comment by nrenner** [comment]
I haven't actually been using these tools, as the Analytic Difference Engine is not globally available and "Cool Name Goes Here" is hammering the main API. I just noted them myself as examples of such a feature that I long wanted to have for achavi.

Here some examples that came to mind:

* [49714483](https://osmlab.github.io/changeset-map/#49714483)
  ![cs-49714483](https://user-images.githubusercontent.com/1092030/27857365-ac8a9c66-6171-11e7-83fa-1d6d624ab73f.png)
  *Screenshot comparing [openstreetmap.org](https://www.openstreetmap.org/changeset/49714483), [changeset-map](https://osmlab.github.io/changeset-map/#49714483) and [Cool Name Goes Here](http://fred.dev.openstreetmap.org/coolnamegoeshere/#/workbench)*
  IMO this describes the changeset best:
  ```
  [113] modify an object
  [102] add    the tag wheelchair
    [6] add    the tag toilets:wheelchair
    [5] change the tag wheelchair
  ```
* [47628097](https://osmlab.github.io/changeset-map/#47628097)
  In this case summarizing the combination of changed tags would show the retagging of addresses from city to suburb in a concise way, and also hightlight the other kind of change where `addr:city` is just renamed to use the official abbreviation. It would also allow to quickly scan the list for other abbreviations.
  ```
    - | 123 x | addr:suburb |                | Neufrach   |
      |       | addr:city   | Salem-Neufrach | Salem      |

      | 234 x | addr:suburb |                | Saathain   |
      |       | addr:city   | Saathain       | Röderland  |

      ...

    - |  56 x | addr:city   | Sankt Märgen   | St. Märgen |
  ```
  *(sums are made up)*
* [47980360](https://osmlab.github.io/changeset-map/#47980360)
  Again a nice summary from "Cool Name Goes Here":
  ```
  [116] change the tag maxspeed to "walk"
   [45] change the tag maxspeed from "30"
   [30] change the tag maxspeed from "7"
   [23] change the tag maxspeed from "10"
    [9] change the tag maxspeed from "6"
    [6] change the tag maxspeed from "5"
    [2] change the tag maxspeed from "20"
    [1] change the tag maxspeed from "50"
  ```
  or as a table:
  ```
  | 45 x | maxspeed | 30 | walk |
  | 30 x | maxspeed |  7 | walk |
  ...
  ```
  Interesting for context would be that it's all for primary key `highway=living_street` and also the subtags `source:maxspeed=DE:zone30` ([way 169835868](https://osmlab.github.io/changeset-map/#47980360/way/169835868)) and `zone:maxspeed=DE:30` ([way 305956789](https://osmlab.github.io/changeset-map/#47980016/way/305956789)) would immediately show the inconsistency of the change.

**Comment by batpad** [comment]
@willemarcel just want to put this on your radar in case you are able to find time to work on this - this is still the no 1 feature I miss when looking at changeset-map ..

**Comment by willemarcel** [comment]
@batpad Good!! I'll dive into it tomorrow!

**Comment by willemarcel** [comment]
This is already available. I'm closing the issue, if someone has some additional request, reopen it please.
