### ISSUE TITLE
Make isolated nodes bigger

### ISSUE THREAD

**Issue by willemarcel** [osmlab/changeset-map#106]
Sometimes is very difficult to visualize where the isolated nodes of the changeset are. What do you think about making it a bit bigger?

![new2](https://cloud.githubusercontent.com/assets/126868/24095141/ab732170-0d81-11e7-81a9-90cce26f60a3.gif)

**Comment by planemad** [comment]
@rasagy escalating this as its too easy to miss features, especially when isolated POIs are created by a new user like this.

<img width="277" alt="screenshot 2017-03-23 11 47 18" src="https://cloud.githubusercontent.com/assets/126868/24234476/9103de4e-0fbe-11e7-9516-87daeb9e9b50.png">

cc @ajithranka

**Comment by rasagy** [comment]
@planemad Can you also share the changeset id so I can test with this dataset?

**Comment by planemad** [comment]
Better one:

<img width="330" alt="screenshot 2017-03-23 11 55 36" src="https://cloud.githubusercontent.com/assets/126868/24234699/b1e0817a-0fbf-11e7-875b-c21d96294673.png">
http://osmlab.github.io/changeset-map/#47072699

**Comment by rasagy** [comment]
This is done. Tracking feedback around the node size at different zoom level and other changes on #125.
