### ISSUE TITLE
Add support for relations

### ISSUE THREAD

**Issue by ajithranka** [osmlab/changeset-map#108]
Changes needed:

- Add relations to the overpass adiff query.
- Flatten features inside the `relations` key before rendering on the map.
- Remove `relations` key from the props diff.

Related to #35 and #94.

cc: @geohacker @batpad @kepta

**Comment by willemarcel** [comment]
It's strange that it's showing the bbox of 3 modified relations of this changeset: https://osmlab.github.io/changeset-map/#46788673

**Comment by rasagy** [comment]
Relations now show up as a thin bounding box, colored according to the action.

### Examples:

<img width="1000" alt="screenshot 2017-04-03 15 28 23" src="https://cloud.githubusercontent.com/assets/1117531/24604992/ab8b9ddc-1884-11e7-8edb-5c21401c00fd.png">

[Typical example: `47211052`](https://osmlab.github.io/changeset-map/#47211052)

---

<img width="1091" alt="screenshot 2017-04-03 15 30 46" src="https://cloud.githubusercontent.com/assets/1117531/24605010/b60a62ca-1884-11e7-9136-fead6ed76251.png">

[Example with relation bbox larger than changeset bbox: `46894721`](https://osmlab.github.io/changeset-map/#46894721)

---

<img width="1001" alt="screenshot 2017-04-03 15 39 54" src="https://cloud.githubusercontent.com/assets/1117531/24605014/bb102002-1884-11e7-85f1-a94be2f15d7c.png">

[Example with crazy number of relation bbox: `47072405`](https://osmlab.github.io/changeset-map/#47072405) — shared by @nikhilprabhakar in #120

---

I’m not sure if this is perfect — Does it clash too much with how a `way` is shown? Is a bounding box a ~correct~ _best_ representation of a relation? 

I also feel that edge cases like the last one make it extremely important to have more control over what is being shown. We should have a toggle button for show/hide `node`, `way`, `relation`, that might also solve other concerns in #125.

cc @ajithranka @planemad @geohacker @batpad @manoharuss

---

> It's strange that it's showing the bbox of 3 modified relations of this changeset: https://osmlab.github.io/changeset-map/#46788673
@willemarcel That seems to be what OSM also shows in the [changeset details](https://www.openstreetmap.org/changeset/46788673) — three other adminstrative boundaries that have the edited way as a relation member.

**Comment by rasagy** [comment]
>We should have a toggle button for show/hide node, way, relation, that might also solve other concerns in #125.

This is now live: #138

Closing this ticket, feel free to re-open if anyone has more thoughts on visualizing relations (or have interesting changesets to share!) :)

**Comment by planemad** [comment]
Thanks @rasagy @ajithranka this is 👍 for all the complexity we need to show. Lets gather more user feedback and ideas for later iterations.
