### ISSUE TITLE
Unable to view tag differences of a highway

### ISSUE THREAD

**Issue by ramyaragupathy** [osmlab/changeset-map#115]
Here is a [way on OpenStreetMap](https://www.openstreetmap.org/way/478825377/history), for which `highway` key has been changed from `unclassified` -> `tertiary`. This is part of [Changeset - 46620937](https://www.openstreetmap.org/changeset/46620937#map=7/59.070/129.339).

This way can be visualised on changeset-map with this link http://osmlab.github.io/changeset-map/#46620937/way/478825377.

But once deselected, way disappears. There's no way to look at this highway again. Ideally I expect a pop up with the tag difference listed.
![changeset](https://cloud.githubusercontent.com/assets/12103383/24183645/a8fe6430-0eef-11e7-8243-cf4f023a376a.gif)

cc @ajithranka @geohacker

**Comment by ramyaragupathy** [comment]
Similar case http://osmlab.github.io/changeset-map/#47023035/node/3291970806, but here node is not highlighted at all.  
OpenStreetMap history: https://www.openstreetmap.org/node/3291970806/history

**Comment by bsrinivasa** [comment]
Adding a similar case here.
http://osmlab.github.io/changeset-map/#46728124/way/5671661
The changeset map stops responding after an initial pan or zoom. 

OSM Link: http://www.openstreetmap.org/way/5671661

**Comment by bsrinivasa** [comment]
http://osmlab.github.io/changeset-map/#39563991/way/46130066

OSM link: https://www.openstreetmap.org/way/46130066/history#map=17/40.80752/-73.92463

**Comment by ajithranka** [comment]
[#46620937/way/478825377](http://osmlab.github.io/changeset-map/#46620937/way/478825377)
  - Fetched from overpass ([query](http://overpass-api.de/api/interpreter?data=[out:xml][adiff:%222017-03-06T11:26:35Z,%22,%222017-03-06T12:38:41Z%22];(node(bbox)(changed);way(bbox)(changed););out%20meta%20geom(bbox);&bbox=126.3848400,58.8076030,132.2933267,59.3307196))
  - Feature changed from version 16 to 18, no version 17 in the xml
  - Changeset-map fails to set a `changeType` in [geojsonChanges.js#L54](https://github.com/osmlab/changeset-map/blob/gh-pages/js/geojsonChanges.js#L54)

[#47023035/node/3291970806](http://osmlab.github.io/changeset-map/#47023035/node/3291970806)
  - Fetched from S3 ([link](http://s3.amazonaws.com/mapbox/real-changesets/production/47023035.json))
  - Node 3291970806 ([history](https://www.openstreetmap.org/node/3291970806/history)) was modified in the changeset but is not part of the json
  - Changeset-map fails when trying to select the features [render.js#L104](https://github.com/osmlab/changeset-map/blob/gh-pages/js/render.js#L104)

[#46728124/way/5671661](http://osmlab.github.io/changeset-map/#46728124/way/5671661)
  - Fetched from S3 ([link](http://s3.amazonaws.com/mapbox/real-changesets/production/46728124.json))
  - Way 5671661 ([history](http://www.openstreetmap.org/way/5671661/history)) was modified but is not part of the json
  - Changeset-map fails when trying to select the features [render.js#L104](https://github.com/osmlab/changeset-map/blob/gh-pages/js/render.js#L104)

[#39563991/way/4613006](http://osmlab.github.io/changeset-map/#39563991/way/46130066)
  - Fetched from overpass ([query](http://overpass-api.de/api/interpreter?data=[out:xml][adiff:%222016-05-25T18:58:11Z,%22,%222016-05-25T18:58:21Z%22];(node(bbox)(changed);way(bbox)(changed););out%20meta%20geom(bbox);&bbox=-73.9371067,40.8027622,-73.9221873,40.8143291)
  - Way 46130066 ([history](http://www.openstreetmap.org/way/46130066/history)) was modified but version number stays at 7 in the xml
  - OSM shows the version as 8
  - Changeset-map fails to set a changeType in [geojsonChanges.js#L54](https://github.com/osmlab/changeset-map/blob/gh-pages/js/geojsonChanges.js#L54)

cc: @batpad @geohacker

**Comment by geohacker** [comment]
* Case 2 is a known problem because of the way we store adiffs on S3 and https://github.com/drolbr/Overpass-API/issues/346
* Case 3, let's raise upstream https://github.com/drolbr/Overpass-API

**Comment by ajithranka** [comment]
PR #121 should fix case 1 and case 3 errors. @ramyaragupathy @bsrinivasa, please cross-check and confirm. If 👍, I'll publish to npm.

- [#46620937/way/478825377](http://osmlab.github.io/changeset-map/#46620937/way/478825377)
- [#39563991/way/46130066](http://osmlab.github.io/changeset-map/#39563991/way/46130066)

**Comment by ramyaragupathy** [comment]
Looks good to me @ajithranka

**Comment by ajithranka** [comment]
Fixed. No next actions.
