### ISSUE TITLE
Redesigning how features are visualized

### ISSUE THREAD

**Issue by rasagy** [osmlab/changeset-map#125]
Based on feedback from #40, #68, #105, #106, here’s a WIP style for visualizing features.

Current changes are pushed to http://changeset-map.surge.sh/

**Legend:**
<img width="847" alt="changeset_map - legend" src="https://cloud.githubusercontent.com/assets/1117531/24330442/c24d406a-123b-11e7-8393-26be53ebb7c0.png">

**Color palette:**
<img width="906" alt="screenshot 2017-03-24 18 11 36" src="https://cloud.githubusercontent.com/assets/1117531/24294658/7c68f4ce-10bd-11e7-9595-c5217be39f73.png">

**Color palette (Color blind: Deuteranopia):**
<img width="906" alt="screenshot 2017-03-24 18 12 34" src="https://cloud.githubusercontent.com/assets/1117531/24294657/7c67c45a-10bd-11e7-887c-aa21b71e0fa4.png">

**Some screenshots:**
![changeset-colors](https://cloud.githubusercontent.com/assets/1117531/24295071/2784d7be-10bf-11e7-89f6-1fde4d684ba8.gif)
<img width="698" alt="screenshot 2017-03-24 18 04 43" src="https://cloud.githubusercontent.com/assets/1117531/24294660/7c6f65e8-10bd-11e7-9cf1-2e9781d7a9fd.png">
<img width="769" alt="screenshot 2017-03-24 18 01 44" src="https://cloud.githubusercontent.com/assets/1117531/24294659/7c6eda6a-10bd-11e7-9021-017609708a77.png">

**Interesting examples:**
- [`45841809`](http://changeset-map.surge.sh/#45841809)
- [`46705455`](http://changeset-map.surge.sh/#46705455)
- [`46923961`](http://changeset-map.surge.sh/#46923961)
- [`47054502`](http://changeset-map.surge.sh/#47054502)
- [`37722848`](http://changeset-map.surge.sh/#37722848)

I’ll follow up with more details on what has been changed (and why). Happy to hear feedback on this as well. :)

cc @ajithranka @geohacker @batpad @planemad @manoharuss @willemarcel

**Comment by willemarcel** [comment]
Congratulations, @rasagy ! It looks great!

**Comment by planemad** [comment]
This is great @rasagy. My only feedback would be that it would be good to be able to see details of the geometries even when zoomed out. This forces me to zoom in, when I could otherwise get an idea of the shapes in the initial view.

**Comment by iandees** [comment]
One thing I was thinking about when I saw https://github.com/osmlab/changeset-map/issues/110 was that there could be a button or key shortcut to temporarily make all the changeset features on the map larger/brighter. i.e. if you hold down the "z" key on the keyboard everything glows and gets bigger until you let it go. Then you can see where changes are while zoomed out and easily switch back to a more fine-grained default view.

**Comment by rasagy** [comment]
@planemad Agreed, while I focused on highlighting nodes, for larger changeset the low zoom level isn’t very helpful.


**Where it works well**:

<img width="875" alt="screenshot 2017-03-26 11 27 07" src="https://cloud.githubusercontent.com/assets/1117531/24329664/d7104120-122a-11e7-8de9-e5b2fb44de31.png">
<img width="863" alt="screenshot 2017-03-26 11 15 56" src="https://cloud.githubusercontent.com/assets/1117531/24329665/d7159440-122a-11e7-9104-d90debd56c61.png">


**Where it doesn’t work well**:

<img width="1240" alt="screenshot 2017-03-26 10 28 41" src="https://cloud.githubusercontent.com/assets/1117531/24330182/9d30def4-1236-11e7-95de-8da1bcae5fab.png">
<img width="1280" alt="screenshot 2017-03-26 10 26 36" src="https://cloud.githubusercontent.com/assets/1117531/24330183/9d37e0a0-1236-11e7-9456-35f6185d4d52.png">

I’m going to now focus on reducing the emphasis on nodes at lower zoom levels, so that we can get a better overview.

> that there could be a button or key shortcut to temporarily make all the changeset features on the map larger/brighter
@iandees Interesting thought! I’m going to try and see if I can get the balance without having a need to toggle the view — in an ideal case you shouldn’t be expected to spend time in toggling the style — but I think mapping keyboard shortcuts to the filters might be helpful as well. cc @ajithranka

**Comment by rasagy** [comment]
Based on comments from @planemad, @iandees as well as feedback from the Data team at Mapbox, I worked more on the feature styling, this time focused on reducing the emphasis on nodes at low zoom levels and getting the balance between nodes & ways at higher zoom levels.

Here are some examples that compare the old style, the WIP style I shared above, and the v2 style based on the feedback.

### Complex changeset: `47166247`: [Old](https://osmlab.github.io/changeset-map/#47166247), [WIP](http://changeset-map.surge.sh/#47166247), [v2](http://changeset-map-v2.surge.sh/#47166247)
<img width="1280" alt="screenshot 2017-03-27 19 41 23" src="https://cloud.githubusercontent.com/assets/1117531/24389101/b1c7e972-139c-11e7-8584-78c36d82490a.png">

### Complex changeset: `47054502`: [Old](https://osmlab.github.io/changeset-map/#47054502), [WIP](http://changeset-map.surge.sh/#47054502), [v2](http://changeset-map-v2.surge.sh/#47054502)
<img width="1280" alt="screenshot 2017-03-27 19 45 17" src="https://cloud.githubusercontent.com/assets/1117531/24389221/967b1c9c-139d-11e7-8d8b-563f3cc8d645.png">

### Details (zoomed in): `47054502`: [Old](https://osmlab.github.io/changeset-map/#47054502), [WIP](http://changeset-map.surge.sh/#47054502), [v2](http://changeset-map-v2.surge.sh/#47054502)
<img width="1280" alt="screenshot 2017-03-28 10 01 30" src="https://cloud.githubusercontent.com/assets/1117531/24389306/181c9000-139e-11e7-869c-d61648bb8691.png">

### Changeset that is clustered in two areas: `46923961`: [Old](https://osmlab.github.io/changeset-map/#46923961), [WIP](http://changeset-map.surge.sh/#46923961), [v2](http://changeset-map-v2.surge.sh/#46923961)
<img width="1280" alt="screenshot 2017-03-27 20 04 52" src="https://cloud.githubusercontent.com/assets/1117531/24389333/5296f6a8-139e-11e7-8e2e-5bcdef9de763.png">

### Isolated nodes along with a small cluster: `47079752`: [Old](https://osmlab.github.io/changeset-map/#47079752), [WIP](http://changeset-map.surge.sh/#47079752), [v2](http://changeset-map-v2.surge.sh/#47079752)

<img width="1280" alt="screenshot 2017-03-27 19 55 50" src="https://cloud.githubusercontent.com/assets/1117531/24389407/e318fb18-139e-11e7-9cc7-023e24c9e3d5.png">

### Two isolated nodes: `47072699`: [Old](https://osmlab.github.io/changeset-map/#47072699), [WIP](http://changeset-map.surge.sh/#47072699), [v2](http://changeset-map-v2.surge.sh/#47072699)
<img width="1280" alt="screenshot 2017-03-27 20 01 30" src="https://cloud.githubusercontent.com/assets/1117531/24389385/b65e152c-139e-11e7-882d-8cc5671a8796.png">

PS: I’m staging these styles using surge, which means these links are temporary and might be overwritten once we make these changes live.

**Comment by planemad** [comment]
@rasagy this is a big improvement. I think having big nodes still ads a lot of visual noise since they are not relevant to inspect at a low zoom level. The only nodes that are relevant for a reviewer are those that are tagged which is currently hidden among all the untagged ones https://github.com/osmlab/changeset-map/issues/4

<img width="652" alt="screen shot 2017-03-28 at 10 28 31 am" src="https://cloud.githubusercontent.com/assets/126868/24389709/6380e91c-13a1-11e7-8a94-77a403bd450c.png">

Achavi does this nicely and only shows the nodes that are tagged to be interactive https://overpass-api.de/achavi/?changeset=47166247
<img width="374" alt="screen shot 2017-03-28 at 10 28 43 am" src="https://cloud.githubusercontent.com/assets/126868/24389710/6382d3da-13a1-11e7-9bed-488edf3be374.png">

**Comment by maning** [comment]
Deleted objects rendering is confusing (left-changesetmap, right-JOSM)

![screen shot 2017-03-28 at 21 01 19](https://cloud.githubusercontent.com/assets/353700/24413664/c23e4eb0-13f9-11e7-8f67-d5f056f81b9c.png)![screen shot 2017-03-28 at 21 01 13](https://cloud.githubusercontent.com/assets/353700/24413665/c2497cd6-13f9-11e7-9b39-d40cc4da5550.png)

**Comment by planemad** [comment]
Found a good changeset to test against. Its been very hard to figure out to read this in changeset-map
- https://osmcha.mapbox.com/47393150/
- https://overpass-api.de/achavi/?changeset=47393150

**Comment by rasagy** [comment]
@planemad Thanks for that feedback! I’m going to work on reducing the two halo effects a bit. 

I want to avoid reducing the black halo too much because I want to support edge cases where only a few isolated nodes are present, like:

![image](https://cloud.githubusercontent.com/assets/1117531/24598024/f1ea611e-1866-11e7-9efd-9e1ce7c13855.png)
https://osmlab.github.io/changeset-map/#47072699

In the screenshot you shared, white halo doubles up in areas where the modified way hasn’t changed the geometry. I’m going to work on improving the filter so untagged nodes (not selectable) don’t have a white halo around them, and reduce the size of other halo.

**Comment by rasagy** [comment]
@planemad Here’s an update on the halo:

I’ve reduced the size and the opacity of the dark halo on high zoom level — this lets you see the underlying imagery details at a higher zoom level, while making the features stand out from the satellite layer at low zoom levels.

![changeset-dark-halo](https://cloud.githubusercontent.com/assets/1117531/24608174/18b22ddc-1893-11e7-833e-8b5e5f85da6a.gif)

The highlight for selected state needs to stand out from the default background (and the satellite layer), so couldn’t get a darker color to work. Instead, I’ve reduced the size and the brightness of the light grey:

<img width="1277" alt="screenshot 2017-04-03 17 06 56" src="https://cloud.githubusercontent.com/assets/1117531/24608143/df693962-1892-11e7-8003-040221370bcb.png">

Changes pushed to [http://osmlab.github.io/changeset-map/](http://osmlab.github.io/changeset-map/#47393150)

cc @ajithranka @bsrinivasa

**Comment by rasagy** [comment]
This got shipped, closing this ticket. Will do a short post about the design decisions (and maybe a wiki/legend for sizes/interactivity) in the next few days.

![changeset-map-over-time-v2- edit](https://cloud.githubusercontent.com/assets/1117531/24859746/8b22096a-1e0f-11e7-8cfe-8c09758bd623.gif)
http://osmlab.github.io/changeset-map/#47393150

cc @ajithranka @geohacker @batpad @planemad
