### ISSUE TITLE
Separate out OSM tags and metadata tags in tag diff view

### ISSUE THREAD

**Issue by batpad** [osmlab/changeset-map#13]
Some of the properties in the tag diff view are actual tags for the feature in OpenStreetMap and some are metadata tags - like `changeset`, `timestamp`, etc.

These should possibly be visually separated in some way.

List of metadata tags: `timestamp`, `version`, `changeset`, `user`, `uid`, `changeType`

cc @planemad @ajithranka 

I'm not sure what this visual separation should look like, and this is possibly not urgent, but filing so that we track this.

**Comment by ajithranka** [comment]
Done #130.

<img width="423" alt="screen shot 2017-04-07 at 3 46 08 pm" src="https://cloud.githubusercontent.com/assets/11095038/24796120/64a6e6b0-1ba9-11e7-8089-f73e6fb74d0e.png">
