### ISSUE TITLE
Visualize changeset on Bing satellite image.

### ISSUE THREAD

**Issue by Yurasi** [osmlab/changeset-map#134]
Hi everyone :wave:
Thank you for your great work.:bow: It helps us a lot.
While was working at OSMCHA, I found several cases like this:
https://osmcha.mapbox.com/47299001/ the changesets not coincide on Mapbox imagery, but yes  on Bing. I think that will be very good if in the tool exist the option of choose between these images. This will make our work faster, without the need to download in some cases the change in JOSM. Is possible that we can see the changesets too on Bing Satellite Imagery? :pray:

**Comment by planemad** [comment]
👍 it would be super handy to be able to use Bing as well which is the source for most OSM contributions. Bing imagery uses the quadkey format, and it looks like it should be possible to add this in mapbox-gl-js https://github.com/mapbox/mapbox-gl-js/pull/2805 , possible documentation https://github.com/mapbox/mapbox-gl-js/issues/4137

**Comment by rasagy** [comment]
@Yurasi Thanks a lot, glad this is helping! 

> Is possible that we can see the changesets too on Bing Satellite Imagery? 🙏
Yes, we’ll see how to quickly add Bing Satellite imagery as well. Closing this ticket and tracking this in the satellite toggles ticket (#89), reposting @planemad’s comment there for future reference.

Do share any other feedback that you have! 🙇
