### ISSUE TITLE
Add links to data tools

### ISSUE THREAD

**Issue by planemad** [osmlab/changeset-map#137]
As changeset-map is becoming the central tool to analyze a changeset, it would be extremely useful to embed links to the various data investigation tools that a reviewer can jump into from the map. Different tools help to analyze different features effectively and we should leave the choice open for the reviewer to decide what is best.

Like https://github.com/osmlab/changeset-map/issues/118 this might be duplicating information that is visible on https://osmcha.mapbox.com , but its known that osmcha will never have every single changeset in OSM history, so we still need a mechanism to have this within changeset-map itself. 

**User level**
- User changesets with comments http://resultmaps.neis-one.org/osm-discussion-comments?uid=115894
- Comments by user http://resultmaps.neis-one.org/osm-discussion-comments?uid=115894&commented
- hdyc http://hdyc.neis-one.org/?DaveF

**Changeset level**
- JOSM http://127.0.0.1:8111/import?url=http://www.openstreetmap.org/api/0.6/changeset/47166247/download
- osmcha https://osmcha.mapbox.com/47166247/
- achavi https://overpass-api.de/achavi/?changeset=47166247
- osmhv http://osmhv.openstreetmap.de/changeset.jsp?id=47166247

**Feature level**
- http://osmlab.github.io/osm-deep-history/#/relation/12

This would be a changing list as there might be new community tools while existing ones might go away. So maybe its best to tuck them under a extra options menu.

**Comment by ajithranka** [comment]
Done after #140 and #141.

**Changeset and user level**
<img width="355" alt="screen shot 2017-04-07 at 3 25 35 pm" src="https://cloud.githubusercontent.com/assets/11095038/24795321/9e6a67c6-1ba6-11e7-900e-513afe818e21.png">

**Feature level**
<img width="404" alt="screen shot 2017-04-07 at 3 25 52 pm" src="https://cloud.githubusercontent.com/assets/11095038/24795325/a0bf892a-1ba6-11e7-9d77-5ca9519b6578.png">

**Comment by sun-geo** [comment]
I agree, the changeset comment is currently not displayed.
