### ISSUE TITLE
Link to a help page & RSS feed of local changesets?

### ISSUE THREAD

**Issue by DaveF63** [osmlab/changeset-map#144]
Hi
I'm loving the latest features, it's fast becoming my go-to validator.

Could a link to a help page be added to clarify the new features (for example, what do the different colours of the rectangles signify? In certain [changesets](http://osmlab.github.io/changeset-map/#47798521) multiple boundary rectangles of varying colours are displayed )

This maybe a bit out of scope, but could an RSS feed of local changesets be added? Similar to [WhoDidIt](http://simon04.dev.openstreetmap.org/whodidit/) 
It would save a bit of tie copy-pasting changeset id's into the input box.

Thanks
DaveF

**Comment by ajithranka** [comment]
Hi @DaveF63, thanks for the great feedback!

We'll add more documentation soon (#146) and that should be of help. In the mean time, please feel free to open an issue on anything that might be confusing in the UI.

> This maybe a bit out of scope, but could an RSS feed of local changesets be added?

I feel this might be out of scope as well. We use [OSMCHA](http://osmcha.mapbox.com/) as our primary frontend for viewing changesets. It integrates changeset-map and there's a comprehensive set of filters (including bounding box) that should be useful for tracking local changesets.

We are starting work on a new frontend for OSMCHA [here](https://github.com/mapbox/osmcha-frontend) and it's a great time to make feature requests. This [ticket](https://github.com/mapbox/osmcha-frontend/issues/2) is a good starting point.
