### ISSUE TITLE
A couple of UI appearance suggestions

### ISSUE THREAD

**Issue by ajithranka** [osmlab/changeset-map#150]
Moved here from [osmcha-frontend#15](https://github.com/mapbox/osmcha-frontend/issues/15).

---
Hi
I'm finding this project very useful.

Could changeset descriptions be added to the dialog so it can been read in fullscreen mode? It's useful as a guide as to what was edited.
Could the dialog be collapsible to an icon & slightly transparent when open?

![capture](https://cloud.githubusercontent.com/assets/9528328/25290172/9f42241c-26c4-11e7-9593-dfb8c69b5bfb.JPG)
---

cc: @DaveF63 @rasagy

**Comment by rasagy** [comment]
@DaveF63 Thanks for the inputs! I think a collapsable panel makes a lot of sense, especially to hide the filter section. I’m going to pair this up with the thoughts on making this responsive (#133), and see if we can do something that works best for both mobile and desktop/tablet.

This might take a while though, will keep this ticket + #133 updated when I jump into this!

**Comment by rasagy** [comment]
@DaveF63 Closing this, and tracking the UI design in #133 and the changeset comment in #118.
