### ISSUE TITLE
Link changeset ids to osmcha

### ISSUE THREAD

**Issue by planemad** [osmlab/changeset-map#156]
It would be great to have changeset ids linked to the osmcha url for inspection.

<img width="446" alt="screen shot 2017-06-19 at 12 16 05 pm" src="https://user-images.githubusercontent.com/126868/27301721-25a04514-54e9-11e7-8aa1-602a0743e817.png">

cc @rasagy

**Comment by willemarcel** [comment]
This feature is already available!
