### ISSUE TITLE
Show features with only property changes or only geometry changes

### ISSUE THREAD

**Issue by ajithranka** [osmlab/changeset-map#16]
Identify a way to show features with only property changes or features with only geometry changes.

**Comment by ajithranka** [comment]
Would this be useful @planemad @batpad? If not, let's close this issue for now and revisit later.

**Comment by planemad** [comment]
Ideally the visualization of both the table and map should be crystal clear on what has changed. We shouldn't need to explicitly say this was just a property or geometry change.

As a first step we could just make the table diff better https://github.com/osmlab/changeset-map/issues/88
