### ISSUE TITLE
empty gray map in Firefox

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/changeset-map#174]
* **I'm submitting a ... **

  - [x] bug report
  - [ ] ~~feature request~~ 
  - [ ] support / question

## *Brief Description*

I opened http://osmlab.github.io/changeset-map/#37859458 in attempt to investigate reported disappearance of nature reserve

## What  is the current behaviour, (attach relevant screenshots) ?

![selection_015](https://user-images.githubusercontent.com/899988/40140574-9ba30b7e-5953-11e8-838a-b177e4efde24.png)

## What  is the expected behaviour ?

Always, I tried also http://osmlab.github.io/changeset-map/#58970843

## When does this occur ?

Always

## How do we replicate the issue ?

1. open http://osmlab.github.io/changeset-map/#37859458

## Please tell us about your environment:

- Firefox 60.0 (64-bit)
- Ubuntu 16
- https://get.webgl.org/ reports that webgl is working

## Other Information / context:

I have

Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
mapbox-gl.js:195:774
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
mapbox-gl.js:187:1639
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
mapbox-gl.js:195:774
Error: WebGL: No further warnings will be reported for this WebGL context. (already reported 32 warnings)
mapbox-gl.js:195:774

in console

**Comment by matkoniecz** [comment]
I tested in Chromium Browser, everything works fine. I will try a clean Firefox install.

**Comment by matkoniecz** [comment]
With fresh Firefox effect is exactly the same.

**Comment by batpad** [comment]
In case this is helpful --

I am unable to reproduce on Firefox 60.0 + Ubuntu 16.04. Although, I do see the same errors in the console, so my guess is the issue is probably unrelated to those errors.

This is strange. Are you able to see GL maps at all? Does https://www.mapbox.com/mapbox-gl-js/example/simple-map/ work, for example?

**Comment by matkoniecz** [comment]
I see https://www.mapbox.com/mapbox-gl-js/example/simple-map/ in Chromium, it is not displaying map on my Firefox except footer with link to mapbox on the left and "© Mapbox © OpenStreetMap Improve this map" on the right.

**Comment by batpad** [comment]
Interesting. So this seems to be a problem with Mapbox GL not rendering in your browser. You could try filing an issue with https://github.com/mapbox/mapbox-gl-js/issues with more details about your environment, but this seems to be an issue not specific to changeset-map.

**Comment by matkoniecz** [comment]
reported as https://github.com/mapbox/mapbox-gl-js/issues/6682 though given 523 open issues and PR waiting over year ( https://github.com/mapbox/mapbox-gl-js/pull/4750 ) investigating why my Firefox in particular is broken will be pretty low in importance...
