### ISSUE TITLE
Overpass query syntax error with newer releases

### ISSUE THREAD

**Issue by mmd-osm** [osmlab/changeset-map#177]
https://github.com/osmlab/changeset-map/blob/master/lib/getChangeset.js#L75 uses Overpass QL syntax, which is no longer valid with release 0.7.55:

`relation(bbox)(changed))`

should be:

`relation(bbox)(changed);)`

(missing semicolon added)

**Comment by willemarcel** [comment]
Thank you, @mmd-osm ! Do the versions prior to 0.7.55 accept this new syntax?

**Comment by mmd-osm** [comment]
Yes, the syntax is not new, it's rather the the syntax check in previous versions allowed for this invalid variant without complaining. This has changed in 0.7.55 now. See https://github.com/openstreetmap/openstreetmap-website/issues/1843#issuecomment-387196549 for more details.

**Comment by mmd-osm** [comment]
Closing, as #179 implements the change. Thanks!
