### ISSUE TITLE
license 

### ISSUE THREAD

**Issue by se-na** [osmlab/changeset-map#218]
* **I'm submitting a ... **

  - [x] bug report
  - [ ] ~~feature request~~ 
  - [ ] support / question

## *Brief Description*

I use changeset Map in a Project. After an "npm update" I noticed that the license (?)->Hover-> (c) no longer appears in my small map.
I thought that maybe with the update other problems would disappear. I had the problem that it did not always zoom properly and "Tags added / updated / deleted" was not always displayed, but this wasn't better with the newer version.

I have tried to find the appropriate sections in the code, which could set the Icon and the message, but unfortunately I don't have the time to read into your code further at the moment. So i changed back to the last version.

## What  is the current behaviour, (attach relevant screenshots) ?

![unknown3](https://user-images.githubusercontent.com/55684419/101000971-d9128680-355e-11eb-9c14-f1d0dad8c3a1.png)

## What  is the expected behaviour ?

![unknown2](https://user-images.githubusercontent.com/55684419/101000988-dd3ea400-355e-11eb-8859-2569bce4046a.png)

## When does this occur ?

After npm update.
If the map is small enough

**Comment by willemarcel** [comment]
Thanks for the report, @se-na! I fixed it.
