### ISSUE TITLE
Show a bounding box covering all features

### ISSUE THREAD

**Issue by ajithranka** [osmlab/changeset-map#24]
![bounding-box](https://cloud.githubusercontent.com/assets/11095038/14809360/2335c94a-0baa-11e6-916b-3ec79f95783e.png)

**Comment by batpad** [comment]
Is this really important? We zoom to the extent of the layer anyway .. I guess it's straightforward to draw the bounding box of the changeset, but is this really useful?

cc @planemad

**Comment by planemad** [comment]
Its a good idea to have especially for changes where objects are distributed in a large area. A bbox helps to set context when zooming in/out on the area of interest and avoid getting lost on the map.

**Comment by planemad** [comment]
Example changeset where bounding box is needed: http://osmlab.github.io/changeset-map/#39865489

**Comment by ajithranka** [comment]
Done (#113).
