### ISSUE TITLE
Use the latest version of Mapbox GL JS (v0.17.0)

### ISSUE THREAD

**Issue by ajithranka** [osmlab/changeset-map#31]
Currently at `v0.14.2` but can move to `v0.17.0`. This is a breaking change and will require changing some of the render code. Particularly, `map.featureAt` has to be replaced with `map.queryRenderedFeatures`.

**Comment by planemad** [comment]
This will also fix the satellite layer flickering.

**Comment by batpad** [comment]
We are now using `v0.18.0`. Closing.
