### ISSUE TITLE
Improve styling for modified old/new

### ISSUE THREAD

**Issue by planemad** [osmlab/changeset-map#34]
<img width="295" alt="screenshot 2016-05-02 17 09 13" src="https://cloud.githubusercontent.com/assets/126868/14953584/a4316fe4-1088-11e6-8c32-25c3d37c9900.png">

Its unclear if the colored version is old or new geometry.

cc @ajithranka

**Comment by batpad** [comment]
This also relates to https://github.com/osmlab/changeset-map/issues/9

**Comment by ajithranka** [comment]
Fixed.

The sidebar shows all the colors being used for reference. The styling is a bit cleaner and should help.

<img width="742" alt="screen shot 2016-12-06 at 5 14 18 pm" src="https://cloud.githubusercontent.com/assets/11095038/20924502/b048018a-bbd7-11e6-9050-ebbc09ca3ec2.png">
