### ISSUE TITLE
Relation support

### ISSUE THREAD

**Issue by planemad** [osmlab/changeset-map#35]
Currently relations are not displayed. 

Changeset: http://osmlab.github.io/changeset-map/#39134799 | https://www.openstreetmap.org/changeset/39134799

cc @ajithranka

**Comment by ajithranka** [comment]
Our [overpass adiff query](https://github.com/osmlab/changeset-map/blob/gh-pages/js/overpass.js#L42) right now only supports nodes and ways.

In contrast, Achavi [optionally looks for relations](https://github.com/nrenner/achavi/blob/28766398e3bd9872967783279c6569498508041e/js/OverpassAPI.js#L120-L122) as well.

**Comment by ajithranka** [comment]
Duplicate. Tracking in #108.
