### ISSUE TITLE
OSM/Mapbox attributions showing up twice in the changeset map.

### ISSUE THREAD

**Issue by nikhilprabhakar** [osmlab/changeset-map#37]
The changeset map in _Vandal Hunter II_ shows OSM/Mapbox attributions twice.

![screen shot 2016-05-09 at 3 37 48 pm](https://cloud.githubusercontent.com/assets/11845908/15110029/31262728-15fc-11e6-8f51-868164dc7a0b.png)

**Comment by ramyaragupathy** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/1804

**Comment by ajithranka** [comment]
This should be fixed now.
