### ISSUE TITLE
Unchecking edit type not working as expected

### ISSUE THREAD

**Issue by ramyaragupathy** [osmlab/changeset-map#38]
When [this](https://www.openstreetmap.org/changeset/38509522) changeset is visualised on the map, one feature that is part of the changeset is getting highlighted in spite of unchecking added/modified/deleted options. 
![changesetmap](https://cloud.githubusercontent.com/assets/12103383/15113400/a26da5cc-1611-11e6-9a7c-e8c1f9b36bf0.gif)

**Expected Behaviour:**

Highlight the related feature(s) for a particular kind of edit.

cc @ajithranka @batpad @planemad @chtnha

**Comment by ajithranka** [comment]
This error is fixed now in the current version: [osmlab/38509522](http://osmlab.github.io/changeset-map/#38509522).
