### ISSUE TITLE
Junk data shown on the map

### ISSUE THREAD

**Issue by ramyaragupathy** [osmlab/changeset-map#39]
While [this](https://www.openstreetmap.org/changeset/38460598#map=17/4.75141/-74.08170) changeset is displayed on the map, there is some additional stuff displayed as well, other than the data that is part of the changeset.

![noise](https://cloud.githubusercontent.com/assets/12103383/15113748/cf4ca794-1613-11e6-8c49-0c849fdb5ff7.gif)

cc @ajithranka @planemad @batpad @maning @chtnha

**Comment by planemad** [comment]
This was the test data used to make the style. I'll remove those layers.

**Comment by batpad** [comment]
@planemad any update on this? Should we just switch over to a different style?

**Comment by planemad** [comment]
Already fixed.
