### ISSUE TITLE
Make nodes with tags bigger circles

### ISSUE THREAD

**Issue by maning** [osmlab/changeset-map#4]
This way I can see it better compared to untagged nodes

**Comment by maning** [comment]
Ping! https://osmcha.mapbox.com/47105825/

![screen shot 2017-03-24 at 23 17 26](https://cloud.githubusercontent.com/assets/353700/24306890/2c40c924-10e8-11e7-863a-1e2c8c49df38.png)

A node that is part of a building was also tagged with building=yes.  Different style for tag nodes and untag nodes can help see the errors easily.

**Comment by maning** [comment]
@ajithranka @rasagy

**Comment by ajithranka** [comment]
Done.
