### ISSUE TITLE
Improve map styling

### ISSUE THREAD

**Issue by planemad** [osmlab/changeset-map#40]
Current style:

![untitled3](https://cloud.githubusercontent.com/assets/126868/15142139/52647af0-16c1-11e6-85e8-a3a07e976794.gif)
- Cannot readily distinguish between colors
- Not color blind friendly

**Comment by planemad** [comment]
**Checklist**
- [ ] Can clearly identify deleted objects
- [ ] Can clearly identify modified objects
- [ ] Can clearly identify added objects

**Comment by rasagy** [comment]
This is done. Tracking feedback around the color-blind friendly color palette and other changes on #125.
