### ISSUE TITLE
Wrong order `old`<-> `new` values

### ISSUE THREAD

**Issue by Andygol** [osmlab/changeset-map#47]
Values in red squares are new! They should be in column with new version

https://osmlab.github.io/changeset-map/#39506602
![image](https://cloud.githubusercontent.com/assets/369696/15542008/a05ba558-2297-11e6-9864-9d2fb45329c8.png)

**Comment by batpad** [comment]
@ajithranka ^ do you know why this might be happening?

My hunch here is that the data structure is fine, but while rendering, we don't render an empty `td` in the first column for empty values.

Can you please look? Let me know if I can help.
