### ISSUE TITLE
error when selecting a changeset

### ISSUE THREAD

**Issue by govvin** [osmlab/changeset-map#51]
I get this error message after selecting a changeset: "OSM Query failed. Are you sure you entered a valid changeset id."

The changeset is valid, when viewed on OSM.  Here's a random changeset I've selected: http://osmcha-django-staging.tilestream.net/39658503/

Tried on Firefox and Chromium, on Ubuntu. 

![image](https://cloud.githubusercontent.com/assets/5821688/15644998/abf1be8a-2688-11e6-85a2-d0996f09dfc3.png)

**Comment by batpad** [comment]
@govvin Hm, this works for me.

The only thing I can think of is perhaps the OSM API was experiencing intermittent issues. Could you say whether you are still facing the issue? Thanks!
