### ISSUE TITLE
Clicking a node deselects way, but keeps the property changes open

### ISSUE THREAD

**Issue by planemad** [osmlab/changeset-map#58]
![untitled2](https://cloud.githubusercontent.com/assets/126868/15928493/cff245dc-2e64-11e6-8929-686fee4347b6.gif)

cc @ajithranka

**Comment by planemad** [comment]
http://osmlab.github.io/changeset-map/#39905981

**Comment by ajithranka** [comment]
Fixed. Selecting a node deselects the way and shows the node properties.

![highlight](https://cloud.githubusercontent.com/assets/11095038/20922964/32419e9c-bbd0-11e6-8669-159d72151e1f.gif)
