### ISSUE TITLE
Handle open changesets

### ISSUE THREAD

**Issue by ajithranka** [osmlab/changeset-map#59]
Right now, if we try to load any changeset that's left open, the overpass query fails because there's no `to` timestamp. 

Example: http://osmlab.github.io/changeset-map/#39922619

![screen shot 2016-06-10 at 12 11 57 pm](https://cloud.githubusercontent.com/assets/11095038/15956265/f255f6f0-2f04-11e6-9f0a-8ebb250e4f8f.png)

I'm not sure how we should handle this case. Maybe we can show an error message.

/cc @batpad @planemad

**Comment by batpad** [comment]
@ajithranka I *think* the best way to do this right now is just display an error message to the user so that it's clear what's going on. Something like:

"Sorry, the changeset you are trying to visualize is still open. Please try again after sometime after the changeset has been closed. Thank you."

**Comment by ajithranka** [comment]
Duplicated in #80. Closing this one.
