### ISSUE TITLE
Map showing objects not part of the changeset

### ISSUE THREAD

**Issue by planemad** [osmlab/changeset-map#60]
Stumbled on this strange object from France to USA on http://osmcha-django-staging.tilestream.net/39924332/

<img width="620" alt="screenshot 2016-06-10 15 56 31" src="https://cloud.githubusercontent.com/assets/126868/15961724/e945cd32-2f23-11e6-9d95-e692921281e4.png">

Interestingly this object was not part of the displayed changeset: https://www.openstreetmap.org/way/204915237/history but was edited in http://osmcha-django-staging.tilestream.net/39924363/ by the same user and is not displayed on the map.

👻 in the machine!

cc @ajithranka @batpad

**Comment by batpad** [comment]
@planemad can you tell if the same feature shows up if you look at the changeset in `achavi`?
Thanks.

**Comment by planemad** [comment]
@batpad Does not show up http://overpass-api.de/achavi/?changeset=39924332/

**Comment by batpad** [comment]
oO interesting :(

@ajithranka we probably want to see if there's any difference in the query we make to overpass and the query that achavi makes ... and see what's up :(

**Comment by ajithranka** [comment]
Still here: http://osmlab.github.io/changeset-map/#39924332.

**Comment by ajithranka** [comment]
Seems to be fixed now.
http://osmlab.github.io/changeset-map/#39924332
