### ISSUE TITLE
Add OSM standard style tile layer in black/white

### ISSUE THREAD

**Issue by stephan75** [osmlab/changeset-map#61]
Hello team,
is it possible to add a background layer selector that offers for example the black&white OSM standard Mapnik layer like the one used at https://osm.wno-edv-service.de/boundaries/ ?

Because with the background aireal images used now, some tiny edited nodes are hard to see, even when images are a bit darkened / dimmed.

**Comment by stephan75** [comment]
... or maybe https://github.com/Zverik/leaflet-grayscale can provide an easy-to-implement solution?

**Comment by rasagy** [comment]
We _tried_ to fix this earlier this year by working more on the satellite imagery layer and making it darker+less saturated. Using raster OSM layer styles along with the GL styles is still not as easy. Closing this for now, happy to re-open once we have an easy way to switch between GL & raster styles. cc @ajithranka
