### ISSUE TITLE
Showing a way was deleted when a node was moved

### ISSUE THREAD

**Issue by planemad** [osmlab/changeset-map#63]
A single node was moved in this changeset https://www.openstreetmap.org/changeset/39866191
<img width="706" alt="screenshot 2016-06-15 15 24 46" src="https://cloud.githubusercontent.com/assets/126868/16075688/9147a5fe-330d-11e6-861a-087b410cf230.png">

However changeset map shows that two ways was deleted http://osmlab.github.io/changeset-map/#39866191/way/340632245
<img width="795" alt="screenshot 2016-06-15 15 25 58" src="https://cloud.githubusercontent.com/assets/126868/16075669/7dd04f76-330d-11e6-837f-c1999eb27ad5.png">

The way selected above corresponds to https://www.openstreetmap.org/way/340632245#map=19/47.23514/9.59826

The moved node was part of [this area](https://www.openstreetmap.org/way/340632245#map=19/47.23514/9.59826), but changeset map shows it as a small line.

cc @ajithranka @batpad

**Comment by planemad** [comment]
Achavi shows this correctly https://overpass-api.de/achavi/?changeset=39866191

<img width="191" alt="screenshot 2016-06-15 16 02 57" src="https://cloud.githubusercontent.com/assets/126868/16076760/a6d74e10-3312-11e6-9107-81c7491fa73b.png">

**Comment by ajithranka** [comment]
Fixed after PR #107.

<img width="623" alt="screen shot 2017-03-17 at 3 37 33 pm" src="https://cloud.githubusercontent.com/assets/11095038/24038547/e146e022-0b27-11e7-8127-e5250dbbb9a4.png">

http://osmlab.github.io/changeset-map/#39866191/node/4228820748
