### ISSUE TITLE
Same output for different changeset

### ISSUE THREAD

**Issue by Rub21** [osmlab/changeset-map#67]
http://osmlab.github.io/changeset-map/#40933373 on different id changesets  display the same change. 
![image](https://cloud.githubusercontent.com/assets/1152236/17060360/2ece1a58-4fef-11e6-92c8-f6fa2c8c7864.png)

**Comment by geohacker** [comment]
@Rub21 Can you give another example? I've not been able to reproduce this.

**Comment by ajithranka** [comment]
This were features coming from the default map styling. Has been fixed now.
