### ISSUE TITLE
Newly added nodes are not showing the property table

### ISSUE THREAD

**Issue by jothirnadh** [osmlab/changeset-map#69]
The changeset map shows up the property table representing the tag info if we click on the feature, but it's not working for the `newly added nodes`. It shows up for modification's, but it fails for the newly added nodes. Due to this, it's becoming hard to verify maps.me additions.

ex:
- http://osmcha.mapbox.com/41679223/
- http://osmcha.mapbox.com/39967290/

//cc: @ajithranka @planemad @batpad

**Comment by manoharuss** [comment]
This has been fixed in the new update.
