### ISSUE TITLE
View info of deleted features

### ISSUE THREAD

**Issue by planemad** [osmlab/changeset-map#7]
This is a changeset with many bad geometries. Clicking on the deleted geometries (red) should atleast display the object id and the old properties if possible.

**Comment by batpad** [comment]
@planemad It should already do that? Is there a specific instance where this does not work?

**Comment by planemad** [comment]
@batpad http://osmlab.github.io/changeset-map/#34752359

**Comment by ajithranka** [comment]
Seems to be working.

<img width="526" alt="screen shot 2016-12-06 at 4 16 26 pm" src="https://cloud.githubusercontent.com/assets/11095038/20922788/6669f30a-bbcf-11e6-8821-a6e0f825971f.png">

**Comment by ajithranka** [comment]
@planemad Can we close this?

**Comment by ajithranka** [comment]
<img width="653" alt="screen shot 2017-03-17 at 3 22 10 pm" src="https://cloud.githubusercontent.com/assets/11095038/24037980/907df178-0b25-11e7-9baf-e0a4aa79f652.png">

This should be fixed now. We have both old (before deletion) and new version of every deleted feature.

**Comment by ajithranka** [comment]
Please reopen if something seems off. 🙇
