### ISSUE TITLE
Tags and metatags in changeset-map are not showingup for nodes

### ISSUE THREAD

**Issue by manoharuss** [osmlab/changeset-map#70]
I have observed that, for POIs and nodes; when clicked changeset map does not give tags and meta tags. Since the node point size is really small, it is hard to click and select as well.

![changesetmapissues](https://cloud.githubusercontent.com/assets/8921295/18260853/6168aff2-740f-11e6-9616-27d1feb213d6.gif)

_Gif for illustration_

The nodes shown in changeset-map are way too small and a bit blurry. It would be nice to have them opaque and a tad bit bigger.

Example changeset: https://osmlab.github.io/changeset-map/#41937519

cc @geohacker @batpad @ajithranka

**Comment by jothirnadh** [comment]
I came across the same issue couple of days back, but at that time it didn't work for newly added nodes https://github.com/osmlab/changeset-map/issues/69 . But not it seems not working for either newly added nodes or modified nodes.

**Comment by manoharuss** [comment]
This has been fixed in the new update. Thanks @ajithranka
