### ISSUE TITLE
Make this importable as a module

### ISSUE THREAD

**Issue by batpad** [osmlab/changeset-map#72]
@geohacker @ajithranka 

Let's use this ticket to hash out the interface and how this will work. But essentially, this should be importable as a JS module in another app, and instantiate a changeset map on any div on the page. 

Currently, the only way to include this is by embedding an `iframe` and this is not ideal for many use-cases.

**Comment by batpad** [comment]
My idea for this:

Get the `render` function to return an `EventEmitter` instance. Then use events to communicate between the module and the outside.

So the module can emit events that can be listened on by the outside, and the outside can `fire` events that the module listens to internally.

@ajithranka do you know of a basic standalone EventEmitter implementation we could use? then I can mock up some code of how this might work.

**Comment by batpad** [comment]
soo .. the way I'm seeing this:

`render` does something like:

`events = new EventEmitter();`
`return events`;

Then from application code that is calling `changeset-map`:

`var changesetMap = render(changesetId);`

To select an item:

`changesetMap.emit('selectFeature', featureId)`

Then code inside `render`:

`changesetMap.on('selectFeature', function(featureId) { ... handle selecting feature ... }`

**Comment by geohacker** [comment]
Happening in #75
