### ISSUE TITLE
Make highlighting more obvious

### ISSUE THREAD

**Issue by planemad** [osmlab/changeset-map#79]
Selected features are currently highlighted in white which is hard to distinguish from modifield old features that also have a white line style.

![untitled2](https://cloud.githubusercontent.com/assets/126868/19763104/4b4cd1d0-9c5a-11e6-8233-7809023fd7e6.gif)

cc @rasagy @ajithranka

**Comment by ajithranka** [comment]
Fixed after PR #87.
