### ISSUE TITLE
Link to mapki

### ISSUE THREAD

**Issue by planemad** [osmlab/changeset-map#84]
From https://github.com/osmlab/wikidata-osm/issues/7 mapki is super useful for specifically tag history on OSM and provides a complete view of tag changes on life of the feature.

We should include a link to this when a feature is selected on changeset-map.

cc @ajithranka @iandees

**Comment by rasagy** [comment]
Based on @iandees’s comment on that thread, we should link to the osmlab project: http://osmlab.github.io/osm-deep-history/#/way/300325882

We can either replace the table header that links to OSM history page with links to both OSM & Mapki links, or add another row with more links like this (Mapki, JOSM #76, iD?)

cc @ajithranka @geohacker

**Comment by rasagy** [comment]
Tracking this in #137.
