### ISSUE TITLE
Reverted features are shown with `deleted` style

### ISSUE THREAD

**Issue by Andygol** [osmlab/changeset-map#85]
https://osmlab.github.io/changeset-map/#44003928
http://osmcha.mapbox.com/44003928/

After reverting previously deleted features they are shown in `red` coloring. It would be great to show them as `modified` at least.

![image](https://cloud.githubusercontent.com/assets/369696/20702366/2d9bfc6c-b620-11e6-9e0a-2e26fbad2855.png)

**Comment by manoharuss** [comment]
Found a similar issue while looking at http://osmcha.mapbox.com/44150589/

The buildings do not seem to be reverted or deleted as they exist on the map with version=1.

Example buildings:

http://www.openstreetmap.org/way/457592669
http://www.openstreetmap.org/way/457592633

Also, the changeset map seems to show edits from other user in this changeset.

![screenshot 2016-12-06 11 17 15](https://cloud.githubusercontent.com/assets/8921295/20914441/a833626e-bba5-11e6-8521-7e30cf5b2374.png)

**Comment by james2432** [comment]
Also having this issue on OSMCHA:
https://github.com/willemarcel/osmcha-django/issues/62

**Comment by ajithranka** [comment]
We moved to using XML for overpass adiff queries in PR #107 and this should fix these errors.

https://osmcha.mapbox.com/44003928/
https://osmcha.mapbox.com/44150589/

Features in ^ are displayed as added.

Please check and let me know if this fixes the issue. 🙇

**Comment by james2432** [comment]
Seems better

**Comment by rasagy** [comment]
This has been fixed. Feel free to reopen if you find anything else like this.
