### ISSUE TITLE
Visualizing tag diffs in the table

### ISSUE THREAD

**Issue by planemad** [osmlab/changeset-map#88]
How osmcha shows tag diffs in a table are super helpful to quickly see what has changed https://osmcha.mapbox.com/44204886/features/way-275602715/

<img width="577" alt="screenshot 2016-12-06 15 53 03" src="https://cloud.githubusercontent.com/assets/126868/20921930/50c59002-bbcc-11e6-9a01-cb70950671cb.png">

This would be great to have in changeset-map by default.

**Comment by ajithranka** [comment]
Showing tags as part of the props table after PR #107.

http://osmlab.github.io/changeset-map/#44204886/way/275602715
<img width="1185" alt="screen shot 2017-03-17 at 3 54 45 pm" src="https://cloud.githubusercontent.com/assets/11095038/24039193/3c6ec0d0-0b2a-11e7-8503-c1b0a2701ed3.png">

We might want to separate out tags from other properties (like user/timestamp/version) in the future, but this works right now.

Closing.
