### ISSUE TITLE
Highlight modified old when clicking on modified new and vice-versa

### ISSUE THREAD

**Issue by batpad** [osmlab/changeset-map#9]
Right now, when you click on a modified feature, it will highlight what you clicked on, but there is no easy way to see the old / new version of the modified feature.

It should ideally highlight both versions of the feature when you click on one.

cc @ajithranka

**Comment by ajithranka** [comment]
Fixed.

![highlight](https://cloud.githubusercontent.com/assets/11095038/20922725/1e0ed378-bbcf-11e6-849a-795ff5cb8d26.gif)
