### ISSUE TITLE
Object display as delete but actually it was not deleted

### ISSUE THREAD

**Issue by Rub21** [osmlab/changeset-map#90]
From : https://osmcha.mapbox.com/37631844/
The objects display as deleted , in this changeset https://www.openstreetmap.org/changeset/37631844

![image](https://cloud.githubusercontent.com/assets/1152236/21865137/d3d09764-d812-11e6-8397-cd28cc985f21.png)
http://osmlab.github.io/changeset-map/#37631844
 However, the object still exist, how is that possible? 
The object exist https://www.openstreetmap.org/way/401803158
![image](https://cloud.githubusercontent.com/assets/1152236/21865235/51a3ba18-d813-11e6-9759-78078be5ca19.png)

cc. @ajithranka @batpad @geohacker

**Comment by Rub21** [comment]
other apps display this: 
![image](https://cloud.githubusercontent.com/assets/1152236/21866236/51707b5e-d817-11e6-9323-aa7ad670b063.png)
http://overpass-api.de/achavi/?changeset=37631844

**Comment by chtnha** [comment]
Flagging the same issue with this changeset: http://osmcha.mapbox.com/45245473/ The forest has been `modified` by the user but not deleted. Any idea on what's is missing in changeset-map? 

![difference](https://cloud.githubusercontent.com/assets/6770741/22053034/23f1d076-dd74-11e6-88b1-b12211c8ff02.png)


 @ajithranka @geohacker @batpad

**Comment by geohacker** [comment]
@Rub21 @chtnha thank you for reporting. Just made a fix for this.
