### ISSUE TITLE
Newly created object display as deleted

### ISSUE THREAD

**Issue by DaveF63** [osmlab/changeset-map#93]
This newly created polygon, along with other objects, is indicated as deleted:
http://osmlab.github.io/changeset-map/#45841809/way/472423613

Is this related to #85 & #90?

**Comment by james2432** [comment]
I also have this issue on osmcha:
https://github.com/willemarcel/osmcha-django/issues/62

**Comment by ajithranka** [comment]
Closing.

[willemarcel/osmcha-django/62#issuecomment-287323898](https://github.com/willemarcel/osmcha-django/issues/62#issuecomment-287323898)
