### ISSUE TITLE
Modified relation not visible

### ISSUE THREAD

**Issue by planemad** [osmlab/changeset-map#94]
The changeset has one modified relation http://www.openstreetmap.org/relation/1819273 . Its not visible on the changeset-map

https://osmcha.mapbox.com/46247388/

cc @rasagy @ajithranka

**Comment by planemad** [comment]
Noticed this was a relation. Blocked by not having relation support https://github.com/osmlab/changeset-map/issues/35

**Comment by ajithranka** [comment]
Duplicate. Tracking in #108.
